#ifndef CHATLIBRARY_GLOBAL_H
#define CHATLIBRARY_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CHATLIBRARY_LIBRARY)
#  define CHATLIBRARYSHARED_EXPORT Q_DECL_EXPORT
#else
#  define CHATLIBRARYSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // CHATLIBRARY_GLOBAL_H
